writePath = '/media/fdavilakurban/TOSHIBA EXT/'
#writePath = '/media/fdavilakurban/TOSHIBA EXT/'
#illustrisPath = '/home/fede/'
illustrisPath = '/home/fdavilakurban/'
#basePath = '/home/fede/TNG300-1/output/'
basePath = '../../../TNG300-1/output/'
units = 'kpc'